export const JOB_LOCATIONS = Object.freeze([
  'Adium (Monteverde)',
  'Aes Sarmiento',
  'Aes Ullum',
  'Argentilemon',
  'Baez Laspiur',
  'Bodegas Callia',
  'CAPS Bermejo',
  'Caps Tamberia',
  'CARF',
  'CCP (Calidra)',
  'Centro Por La Vida',
  'Ceramica San Lorenzo',
  'Clorox',
  'Easy (Better)',
  'Ferva',
  'Genneia',
  'Greif',
  'Grupo Comeca',
  'Hosp Valle Fertil',
  'Hospital Barreal',
  'Hospital Calingasta',
  'Hospital mental (Zonda)',
  'Hospital Pocito',
  'Hospital Sarmiento',
  'Igarreta',
  'La Segunda Seguros',
  'Los Berros',
  'Micro Hospital Berros',
  'Molinos',
  'Padre Bueno',
  'Proviser Sarmiento',
  'Proviser Ullum',
  'Saint Gobain (Placo)',
  'ServiFood',
  'Vicunha',
]);
