-- Make job request images private while preserving access for authenticated app users.
-- Signed URLs are generated by the frontend and expire after one hour.

update storage.buckets
set public = false
where id = 'job-request-images';

drop policy if exists "Job request images read authenticated" on storage.objects;
create policy "Job request images read authenticated"
on storage.objects
for select
to authenticated
using (bucket_id = 'job-request-images');
