export const actionTypeOptions = [
  'Reparación',
  'Cambio',
  'Quitar',
  'Instalación',
  'Revisión',
  'Limpieza',
  'Ajuste',
  'Mantenimiento preventivo',
  'Mantenimiento correctivo',
  'Desobstrucción',
  'Pintura',
  'Soldadura',
  'Otro',
];

export const sectorTypeOptions = [
  'Cocina',
  'Horno',
  'Anafe',
  'Freidora',
  'Heladera',
  'Freezer',
  'Cámara frigorífica',
  'Aire acondicionado',
  'Extractor',
  'Campana',
  'Termotanque',
  'Tanque de agua',
  'Bomba de agua',
  'Cañerías',
  'Desagüe',
  'Baño',
  'Comedor',
  'Depósito',
  'Oficina',
  'Tablero eléctrico',
  'Iluminación',
  'Puerta',
  'Ventana',
  'Piso',
  'Otro',
];
